planner:
  epsilon: 100
  verbose: true
  search_mode: true
  use_dijkstra_heuristic: true
  use_research_heuristic: false
  use_uniform_obstacle_cost: true
  use_multiresolution_motion_primitives: false
  research:
    solve_with_ik_threshold: 0.06
    sum_heuristics: false
    short_distance_mprims_threshold: 0.1
  
robot:
  arm_name: right_arm
  num_joints: 7
  waypoint_time: 0.2
  
debug:
  print_out_path: true

visualizations:
  heuristic: true
  goal: true
  expanded_states: true
  trajectory: false
  collision_model_trajectory: false
  trajectory_throttle: 1

collision_space:
  reference_frame: base_footprint
  resolution: 0.02
  collision_map_topic: collision_map_occ

  occupancy_grid:
    origin_x: -0.6
    origin_y: -1.25
    origin_z: -0.05
    size_x: 1.6
    size_y: 1.6
    size_z: 1.4

reference_frame: base_footprint
fk_service_name: pr2_right_arm_kinematics/get_fk
ik_service_name: pr2_right_arm_kinematics/get_ik


