locations:

  - name: fridge1_1
    pose: 0.5 0.225 0.77 3.14
  - name: fridge1_2
    pose: 0.5 0.45 0.77 3.14
  - name: fridge2_1
    pose: 0.5 0.225 1.11 3.14
  - name: fridge2_2
    pose: 0.5 0.45 1.11 3.14
  - name: fridge3_1
    pose: 0.5 0.25 1.36 3.14
  - name: fridge3_2
    pose: 0.42 0.45 1.36 3.14
  - name: counter1_1
    pose: 0.44 0.96 0.92 3.14
  - name: counter1_2
    pose: 0.32 1.1 0.92 3.14
  - name: counter2_1
    pose: 0.54 1.94 0.98 2.20
  - name: sink_1
    pose: 0.34 1.54 0.8 2.8
  - name: sink_2
    pose: 0.38 1.6 0.92 3.14
  - name: lower_cabinet2_1
    pose: 0.44 1.06 0.55 3.14
  - name: lower_cabinet2_2
    pose: 0.4 0.97 0.61 3.14
  - name: cabinet1_1
    pose: 0.25 1.0 1.35 3.14 
  - name: cabinet1_2
    pose: 0.3 1.3 1.35 3.14 
  - name: cabinet2_1
    pose: 0.36 1.88 1.35 3.14 
  - name: dishwasher_1
    pose: 0.95 2.1 0.3 1.57
  - name: dishwasher_2
    pose: 1.15 2.2 0.4 3.14 
  - name: table_1
    pose: 1.9 0.5 0.85 0
  - name: table_2
    pose: 1.9 0.95 0.9 0
