goal_tolerance:
  xyz: 0.02 0.02 0.02
  yaw: 0.1

object_pose_in_gripper:
  right:
    xyz: -0.20 -0.1 0.0
    rpy: 0.0 0.0 0.0
  left:
    xyz: -0.20 0.1 0.0
    rpy: 0.0 0.0 0.0

use_current_pose_as_start_state: true
start_state:
  right: 0.0359 -0.0635 0.0000 -0.4391 3.0672 -0.5037 -3.0764
  left: -0.1875 -0.1581 0.0000 -0.2151 -2.6618 -0.4157 2.6973
  base: 1.9 0.6 1.57
  spine: 0.0

experiments:

  - name: box000
    goal: palette0
    pre_action: attach
    post_action: detach
    sound_bite: "box 0"
  - name: box001
    goal: shelf1
    pre_action: attach
    post_action: detach
    sound_bite: "box 1"
  - name: box002
    goal: palette2
    pre_action: attach
    post_action: detach
    sound_bite: "box 2"
  - name: box003
    goal: shelf3
    pre_action: attach
    post_action: detach
    sound_bite: "box 3"
  - name: box004
    goal: palette4
    pre_action: attach
    post_action: detach
    sound_bite: "box 4"
  - name: box005
    goal: shelf5
    pre_action: attach
    post_action: detach
    sound_bite: "box 5"
  - name: box006
    goal: palette6
    pre_action: attach
    post_action: detach
    sound_bite: "box 6"
  - name: box007
    goal: shelf7
    pre_action: attach
    post_action: detach
    sound_bite: "box 7"
  - name: box008
    goal: palette8
    pre_action: attach
    post_action: detach
    sound_bite: "box 8"
  - name: box009
    goal: shelf9
    pre_action: attach
    post_action: detach
    sound_bite: "box 9"
  - name: box010
    goal: palette10
    pre_action: attach
    post_action: detach
    sound_bite: "box 10"
  - name: box011
    goal: shelf11
    pre_action: attach
    post_action: detach
    sound_bite: "box 11"
